#!/bin/sh -e

# Default settings when sentinel is running without `link`
# to redis master container and/or
# when sentinel is using the host network stack
# (with --net=host docker run option)

cat << EOF > /etc/sentinel.conf
sentinel monitor "$CLUSTER_NAME" redi01 6379 1
sentinel down-after-milliseconds "$CLUSTER_NAME" 5000
sentinel failover-timeout "$CLUSTER_NAME" 180000
sentinel parallel-syncs "$CLUSTER_NAME" 1
logfile "/var/log/containers/sentinel.log"
EOF

exec redis-server /etc/sentinel.conf --sentinel --loglevel verbose
