data:
  image: cogniteev/echo
  volumes:
    - /data
redisnode1:
  image: redis
  command: >
    redis-server --logfile /data/redisnode1.log
                 --dbfilename redisnode1.rdb
                 --save 30 1
  volumes_from:
    - data

redisnode2:
  image: redis
  command: > 
    redis-server --slaveof master 6379 
                 --logfile /data/redisnode2.log
                 --dbfilename redisnode2.rdb
                 --save 30 1
  links:
    - redisnode1:master
  volumes_from:
    - data

redisnode3:
  image: redis
  command: >
    redis-server --slaveof master 6379
                 --logfile /data/redisnode3.log
                 --dbfilename redisnode3.rdb
                 --save 30 1
  links:
    - redisnode1:master
  volumes_from:
    - data

redissentinel1:
  build: sentinel
  volumes_from:
    - data
  links:
    - redisnode1:master
    - redisnode2
    - redisnode3
  environment:
    SENTINEL_NAME: redissentinel1

redissentinel2:
  build: sentinel
  volumes_from:
    - data
  links:
    - redisnode1:master
    - redisnode2
    - redisnode3
  environment:
    SENTINEL_NAME: redissentinel2

redissentinel3:
  build: sentinel
  volumes_from:
    - data
  links:
    - redisnode1:master
    - redisnode2
    - redisnode3
  environment:
    SENTINEL_NAME: redissentinel3

web:
  build: ./web
  command: uwsgi --socket 0.0.0.0:5000 -w app:app --logto /data/flask.log
  links:
    - redisnode1
    - redisnode2
    - redisnode3
    - redissentinel1
    - redissentinel2
    - redissentinel3

webproxy:
  build: ./web-proxy
  ports:
    - "80:80"
  links:
    - web:upstream1